#!/usr/bin/env ruby

class ProjectCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def command
    @command.split.first  
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def projects
    if command == 'w'
      `ls #{ENV['WORK_PATH']}/`.split
    else
      `ls #{ENV['PROJECTS_PATH']}/`.split
    end
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0

